package com.nbport.ediesb.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2016-07-25T17:03:01.625+08:00
 * Generated source version: 3.0.9
 * 
 */
@WebService(targetNamespace = "http://service.ediesb.nbport.com/", name = "EDIESBServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface EDIESBServicePortType {

    @WebResult(name = "return", targetNamespace = "http://service.ediesb.nbport.com/")
    @RequestWrapper(localName = "callEDIESBPub", targetNamespace = "http://service.ediesb.nbport.com/", className = "com.nbport.ediesb.service.CallEDIESBPub")
    @WebMethod
    @ResponseWrapper(localName = "callEDIESBPubResponse", targetNamespace = "http://service.ediesb.nbport.com/", className = "com.nbport.ediesb.service.CallEDIESBPubResponse")
    public java.lang.String callEDIESBPub(
        @WebParam(name = "arg0", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg5
    );

    @WebResult(name = "return", targetNamespace = "http://service.ediesb.nbport.com/")
    @RequestWrapper(localName = "callEDIESB", targetNamespace = "http://service.ediesb.nbport.com/", className = "com.nbport.ediesb.service.CallEDIESB")
    @WebMethod
    @ResponseWrapper(localName = "callEDIESBResponse", targetNamespace = "http://service.ediesb.nbport.com/", className = "com.nbport.ediesb.service.CallEDIESBResponse")
    public java.lang.String callEDIESB(
        @WebParam(name = "arg0", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "http://service.ediesb.nbport.com/")
        java.lang.String arg4
    );
}
