package com.nbport.ediesb.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2016-07-25T17:03:01.634+08:00
 * Generated source version: 3.0.9
 * 
 */
@WebServiceClient(name = "EDIESBService", 
                  wsdlLocation = "http://169.169.19.33:8888/com.nbport.ediesb.service.EDIESBService?wsdl",
                  targetNamespace = "http://service.ediesb.nbport.com/") 
public class EDIESBService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ediesb.nbport.com/", "EDIESBService");
    public final static QName EDIESBServicePort = new QName("http://service.ediesb.nbport.com/", "EDIESBServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://169.169.19.33:8888/com.nbport.ediesb.service.EDIESBService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EDIESBService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://169.169.19.33:8888/com.nbport.ediesb.service.EDIESBService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EDIESBService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EDIESBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EDIESBService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EDIESBService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EDIESBService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EDIESBService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns EDIESBServicePortType
     */
    @WebEndpoint(name = "EDIESBServicePort")
    public EDIESBServicePortType getEDIESBServicePort() {
        return super.getPort(EDIESBServicePort, EDIESBServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EDIESBServicePortType
     */
    @WebEndpoint(name = "EDIESBServicePort")
    public EDIESBServicePortType getEDIESBServicePort(WebServiceFeature... features) {
        return super.getPort(EDIESBServicePort, EDIESBServicePortType.class, features);
    }

}
